# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: echo "HEY MY MANLY MAN DUDES WHAT IS UP IN DA HAUS"
  displayName: "Greet manly man-dudes"
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "Masquerading as a man with a reason, my charade is the event of the season"'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'README.md'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: Npm@1
  inputs:
    command: 'install'
- task: Grunt@0
  inputs:
    gruntFile: 'gruntfile.js'
    targets: build
    gruntCli: 'node_modules/grunt-cli/bin/grunt'